-- #programa_app


-- MySQL Workbench Synchronization
-- Generated: 2020-03-19 06:23
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Th3Khan

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `seguridad_logro`.`assignment_as_watchmen` 
ADD COLUMN `is_active` INT(1) NOT NULL DEFAULT 1 AFTER `replacement_of`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
